(function(root){
  'use strict';
  root.FitnessNutritionUI=class {
    constructor(ctx){Object.assign(this,ctx);this.date=this.day();this.query='';this.category='';this.limit=12;this.calculationId=null;}
    get state(){return this.getState();}
    normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
    foods(query='',category=''){return this.state.foods.filter(f=>(!category||(f.category||'Mis productos')===category)&&this.normalize([f.name,f.brand,f.barcode].join(' ')).includes(this.normalize(query)));}
    b(label,action,attrs='',style=''){return this.button(label,action,attrs,style);}
    summary(date=this.date){const result=FitnessNutrition.daySummary(this.state,date);if(date===this.day()&&!result.complete){result.target=this.state.targets?.calories??result.target;result.tdee=this.state.targets?.tdee??result.tdee;result.macroTargets=FitnessNutrition.macroTargets(this.state.targets);result.remaining=result.target===null?null:result.target-result.kcal;}return result;}
    safeLink(url,label){try{const link=new URL(url);return link.protocol==='https:'?`<a href="${this.esc(link.href)}" target="_blank" rel="noopener noreferrer">${this.esc(label)}</a>`:'';}catch{return '';}}
    macroCards(s){return `<div class="nutrition-macros grid four">${[['Calorías','kcal',s.target,'kcal'],['Proteínas','protein',s.macroTargets.protein,'g'],['Carbohidratos','carbs',s.macroTargets.carbs,'g'],['Grasas','fat',s.macroTargets.fat,'g']].map(([label,key,target,unit])=>{const remaining=target===null?null:target-s[key],progress=target>0?Math.min(100,s[key]/target*100):0;return `<article class="macro-card"><p class="eyebrow">${label}</p><p><strong>${this.fmt(s[key],key==='kcal'?0:1)} ${unit}</strong>${target===null?'':` <span class="muted">/ ${this.fmt(target,1)} ${unit}</span>`}</p><div class="macro-track" role="progressbar" aria-label="${label} registradas" aria-valuenow="${Math.round(progress)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${progress}%"></span></div><p class="source-note">${remaining===null?'Meta por definir':`${this.fmt(Math.abs(remaining),key==='kcal'?0:1)} ${unit} ${remaining<0?'por encima':'disponibles'}`}</p></article>`;}).join('')}</div>`;}
    hydration(){const logs=FitnessNutrition.waterSummary(this.state,this.date),latest=[...(this.state.weights||[])].filter(w=>w.date<=this.date).sort((a,b)=>b.date.localeCompare(a.date))[0],recommendation=root.FitnessWellness?.hydration(this.state.profile,latest?.weightKg||this.state.profile.initialWeightKg),target=recommendation?.liters,glass=Number(this.state.config.waterGlassMl)||250;return `<section class="card water-card"><div class="toolbar"><div><p class="eyebrow">TU AGUA DEL DÍA</p><h2>${this.fmt(logs.liters,2)} L <span class="muted">${target?'de '+this.fmt(target,1)+' L':''}</span></h2></div><div class="water-glass" aria-hidden="true"><svg viewBox="0 0 70 80" width="56" height="64"><path d="M13 7h44l-6 66H19Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M17 34q9-7 18 0t18 0l-3 36H20Z" fill="currentColor" opacity=".55"/></svg></div></div><p>${logs.glasses} ${logs.glasses===1?'vaso registrado':'vasos registrados'} · ${this.fmt(logs.ml)} ml en esta fecha</p><div class="toolbar">${this.b(`Tomé un vaso · ${glass} ml`,'nutrition-water-add','','primary')}${this.b('Quitar último vaso','nutrition-water-remove',logs.entries.length?'':'disabled')}${this.select('Tamaño de mi vaso','water-glass-ml',glass,[150,200,250,300,350,500].map(v=>[v,v+' ml'])).replace('<select','<select id="water-glass-ml"')}</div><p class="source-note">${target?this.esc(recommendation.basis||'Referencia diaria orientativa según tu perfil.'):'Completa tu perfil para ver una referencia de agua.'} El contador registra el agua que anotas; las bebidas del diario de comida no se suman automáticamente.</p></section>`;}
    render(){const {esc,fmt,field,metric}=this,s=this.summary(),dates=[...new Set([...(this.state.meals||[]).map(m=>m.date),...(this.state.nutritionDays||[]).map(d=>d.date)])].sort().reverse();return this.head('COMIDA Y CALORÍAS','Tu diario de alimentación.','Registra lo que consumes, con sus cantidades. Los alimentos y las porciones quedan guardados por fecha.')+`
      <section class="card nutrition-overview"><div class="toolbar">${field('Fecha del diario','diary-date',this.date,'date',`id="diary-date" max="${this.day()}"`)}${this.b('Ir a hoy','nutrition-today')}</div>${this.macroCards(s)}<p class="source-note">${s.target===null?'Define tus calorías en Perfil para comparar con un objetivo.':'El objetivo de calorías ya contempla tu déficit planificado; no necesitas restarlo de nuevo.'}</p><div class="toolbar">${this.b('Registrar alimento','nutrition-log','','primary')}${this.b('Calcular y registrar porciones','portions')}${this.b('Crear producto por etiqueta','food-edit')}</div></section>${this.hydration()}${this.restaurantCards()}
      <section class="card"><div class="toolbar"><h2>${this.date===this.day()?'Hoy comí':this.dateText(this.date)}</h2><span class="badge">${s.complete?'Día completo':'Registro en curso'}</span></div>${s.entries.map(m=>`<article class="list-row"><div><strong>${esc(m.name)}</strong><p>${esc(m.mealType||'Comida')} · ${fmt(m.kcal)} kcal · ${fmt(m.protein,1)} g proteína</p><p class="muted">${(m.items||[]).map(i=>`${fmt(i.grams,1)} ${esc(i.unit||'g')} de ${esc(i.name)}`).join(' · ')}</p></div><div class="toolbar">${m.items?.length?this.b('Editar registro','nutrition-edit',`data-id="${m.id}"`):''}${this.b('Quitar','meal-remove',`data-id="${m.id}"`)}</div></article>`).join('')||'<p class="empty">Aún no hay comidas registradas en esta fecha.</p>'}<div class="stats">${metric(`${fmt(s.carbs,1)} g`,'carbohidratos')}${metric(`${fmt(s.fat,1)} g`,'grasas')}</div><p>${s.complete&&s.estimatedDeficit!==null?`Balance estimado del día: <strong>${fmt(Math.abs(s.estimatedDeficit))} kcal de ${s.estimatedDeficit>=0?'déficit':'superávit'}</strong> frente al TDEE guardado de ${fmt(s.tdee)} kcal.`:'El déficit estimado se muestra cuando marcas que ya registraste todas las comidas del día.'}</p>${s.entries.length?this.b(s.complete?'Reabrir día':'Ya registré todo el día','nutrition-complete',`aria-pressed="${s.complete}"`):''}<p class="source-note">El balance es una estimación basada en el TDEE y en tu registro; no mide el gasto real del día.</p></section>
      <section class="card"><div class="toolbar"><h2>Recetario</h2>${this.b('Nueva receta','recipe')}</div><div class="grid two">${this.state.recipes.map(r=>{const t=FitnessNutrition.totals(FitnessNutrition.snapshot(this.state.foods,r.items));return `<article class="recipe"><h3>${esc(r.name)}</h3><p>${fmt(t.kcal)} kcal · ${fmt(t.protein,1)} g proteína</p><p class="muted">${esc(r.instructions||'')}</p><div class="toolbar">${this.b('Agregar al día','meal',`data-id="${r.id}"`)}${this.b('Editar receta','recipe',`data-id="${r.id}"`)}${this.b('Eliminar receta','nutrition-delete-recipe',`data-id="${r.id}"`)}</div></article>`;}).join('')||'<p class="muted">Guarda tus preparaciones habituales para registrarlas más rápido.</p>'}</div></section>
      <section class="card"><h2>Buscar alimentos y productos</h2><div class="form-grid">${field('Buscar por nombre, marca o código','food-query',this.query,'search','id="food-query" placeholder="Arroz, pollo, banana, yogur…"')}${this.select('Categoría','food-category',this.category,[['','Todas las categorías'],...[...new Set(this.state.foods.map(f=>f.category||'Mis productos'))].sort().map(c=>[c,c])]).replace('<select','<select id="food-category"')}</div><div id="food-results">${this.catalogRows()}</div><p class="source-note">Catálogo general de <a href="https://fdc.nal.usda.gov/download-datasets/" target="_blank" rel="noopener">USDA FoodData Central (SR Legacy 2018)</a>. Las recetas y marcas pueden variar: ajusta los datos con la etiqueta del producto. Los precios nuevos quedan sin configurar.</p></section>
      <section class="card"><div class="toolbar"><h2>Historial calórico</h2>${this.b('Exportar diario CSV','nutrition-export')}</div>${dates.map(date=>{const d=this.summary(date);return `<div class="list-row"><div><strong>${this.dateText(date)}</strong><p>${fmt(d.kcal)} kcal · ${fmt(d.protein,1)} g proteína · ${d.complete?'Completo':'En curso'}</p><p class="muted">${d.target===null?'Sin objetivo histórico guardado':`Objetivo: ${fmt(d.target)} kcal`}${d.estimatedDeficit===null?'':` · ${fmt(Math.abs(d.estimatedDeficit))} kcal de ${d.estimatedDeficit>=0?'déficit':'superávit'} estimado`}</p></div>${this.b('Ver día','nutrition-date',`data-date="${date}"`)}</div>`;}).join('')||'<p class="muted">Cada fecha con alimentos registrados aparecerá aquí.</p>'}</section>${this.supplements()}`;}
    catalogRows(){const list=this.foods(this.query,this.category),{esc,fmt}=this;return `<p class="muted">${list.length} resultados · ${this.state.foods.length} alimentos y productos guardados</p>${list.slice(0,this.limit).map(f=>`<div class="list-row"><div><strong>${esc(f.name)}</strong><p class="muted">${f.kcal} kcal · ${f.protein} g proteína por 100 ${esc(f.unit||'g')}${f.brand?' · '+esc(f.brand):''}</p></div><div class="toolbar">${this.b('Registrar','nutrition-log',`data-id="${f.id}"`)}${this.b('Editar','food-edit',`data-id="${f.id}"`)}${this.b('Eliminar','nutrition-delete-food',`data-id="${f.id}"`)}</div></div>`).join('')||'<p>No encontramos ese producto. Puedes crearlo con la información de su etiqueta.</p>'}${list.length>this.limit?this.b('Mostrar más','nutrition-more'):''}`;}

    restaurantCards(){return '<section class="card"><h2>Menús y comidas de Panamá</h2><p class="source-note">Referencias editables, no cifras nutricionales oficiales locales. Revisa las porciones antes de guardar. Tus cambios se recuerdan para la próxima vez.</p><div class="grid two">'+FitnessRestaurants.restaurants.map(r=>`<article><h3>${this.esc(r.name)}</h3><p class="source-note">${this.esc(r.notes)} ${this.safeLink(r.sourceUrl,'Consultar menú / fuente')}</p><div class="toolbar">${r.items.map(i=>this.b(this.esc(i.name),'nutrition-restaurant',`data-restaurant="${r.id}" data-id="${i.id}"`)).join('')}</div></article>`).join('')+'</div></section>';}
    restaurantForm(restaurantId,itemId,entry){const r=FitnessRestaurants.restaurants.find(r=>r.id===restaurantId),item=r?.items.find(i=>i.id===itemId),key=entry?.restaurantKey||(restaurantId+'-'+itemId);this.restaurantDraft={id:entry?.id||this.id(),key,name:entry?.name||(r.name+' · '+item.name),date:entry?.date||this.date,mealType:entry?.mealType||'Almuerzo',notes:item?.notes||'',sourceUrl:r?.sourceUrl,components:entry?entry.items.map(i=>({...i,quantity:i.grams,included:true,...Object.fromEntries(['kcal','protein','carbs','fat','cost'].map(k=>[k,(Number(i[k])||0)/i.grams]))})):structuredClone(this.state.config.restaurantTemplates?.[key]||item.components).map(c=>({...c,included:c.included!==false,quantity:c.quantity??1}))};this.drawRestaurant();}
    drawRestaurant(){const d=this.restaurantDraft;this.modal('Personalizar comida',`<form id="restaurant-form"><p class="source-note">Nutrición estimada con alimentos de referencia y cantidades supuestas. Puedes corregir cada cifra por porción según la etiqueta o el restaurante. ${this.esc(d.notes)} ${this.safeLink(d.sourceUrl,'Ver fuente')}</p><div class="form-grid">${this.field('Nombre','name',d.name,'text','required maxlength="180"')}${this.field('Fecha','date',d.date,'date',`required max="${this.day()}"`)}${this.select('Momento','mealType',d.mealType,this.mealOptions())}</div>${d.components.map((c,i)=>`<section class="ingredient-row"><label class="check-label"><input type="checkbox" name="include_${i}" ${c.included?'checked':''}>Incluir ${this.esc(c.name)}</label><p class="source-note">${this.esc(c.quantityLabel||'Valores por una porción')}</p><div class="form-grid">${this.field('Nombre del componente','component_'+i,c.name,'text','required maxlength="180"')}${this.field('Porciones','quantity_'+i,c.quantity,'number','min="0" max="20" step="0.05" required')}${[['kcal','Calorías'],['protein','Proteínas (g)'],['carbs','Carbohidratos (g)'],['fat','Grasas (g)']].map(([k,l])=>this.field(l+' por porción',k+'_'+i,Math.round(c[k]*100)/100,'number','min="0" max="20000" step="0.01" required')).join('')}</div>${c.kind==='drink'?this.b('Cambiar a soda zero','nutrition-drink-zero',`data-index="${i}"`)+this.b('Cambiar a agua','nutrition-drink-water',`data-index="${i}"`):''}</section>`).join('')}<p id="restaurant-total" class="rest-alert" aria-live="polite"></p>${this.actions('Guardar comida en el diario')}</form>`);this.restaurantPreview();}
    rememberRestaurant(){const form=document.querySelector('#restaurant-form');if(!form)return;const v=Object.fromEntries(new FormData(form)),d=this.restaurantDraft;Object.assign(d,{name:v.name,date:v.date,mealType:v.mealType});d.components=d.components.map((c,i)=>({...c,name:v['component_'+i],quantity:Number(v['quantity_'+i]),included:v['include_'+i]==='on',...Object.fromEntries(['kcal','protein','carbs','fat'].map(k=>[k,Number(v[k+'_'+i])]))}));}
    restaurantPreview(){this.rememberRestaurant();try{const t=FitnessNutrition.totals(FitnessNutrition.restaurantSnapshot(this.restaurantDraft.components));document.querySelector('#restaurant-total').textContent=this.fmt(t.kcal)+' kcal · '+this.fmt(t.protein,1)+' g proteína · '+this.fmt(t.carbs,1)+' g carbohidratos · '+this.fmt(t.fat,1)+' g grasas (estimados)';}catch(e){document.querySelector('#restaurant-total').textContent=e.message;}}

    supplements(){const {esc,fmt}=this;return `<section class="card"><div class="toolbar"><h2>Suplementos</h2>${this.b('Agregar envase','supplement')}</div>${this.state.supplements.map(s=>{const d=FitnessCore.supplementDays(s,this.day());return `<article class="list-row"><div><h3>${esc(s.name)}</h3><p>${fmt(s.remainingGrams,1)} g restantes · ${d.daysRemaining===null?'Sin estimación':`${fmt(d.daysRemaining,1)} días aproximados`}</p>${d.replenishmentDate?`<p class="muted">Reposición estimada: ${this.dateText(d.replenishmentDate)}</p>`:''}${d.lowStock?'<p class="badge">Tu envase está por terminarse</p>':''}</div><div>${this.b('Registrar consumo de hoy','consume',`data-id="${s.id}"`)}${this.b('Editar','supplement',`data-id="${s.id}"`)}</div></article>`;}).join('')}<p class="source-note">La dosis la eliges tú. El inventario disminuye solo al registrar un consumo.</p></section>`;}
    picker(label,name,value,unitOverride,snapshot){return `<div class="food-picker">${this.field('Buscar para '+label,'search-'+name,'','search',`data-food-filter="${name}" placeholder="Escribe para filtrar…"`)}${this.select(label,name,value,[...this.state.foods.map(f=>[f.id,`${f.name} · 100 ${(f.id===value&&unitOverride)||f.unit||'g'}`]),...(!this.state.foods.some(f=>f.id===value)&&snapshot?[[value,snapshot.name+' · registro conservado']]:[])])}</div>`;}
    foodForm(fid){const f=this.state.foods.find(f=>f.id===fid)||{},unit=f.unit||'g';this.modal('Alimento o producto por etiqueta',`<form id="food-form" data-id="${this.esc(fid||'')}"><p>Introduce la información de la etiqueta. Si viene por porción, indica cuántos gramos o mililitros tiene esa porción.</p><div class="form-grid">${this.field('Nombre','name',f.name,'text','required maxlength="100"')}${this.field('Marca (opcional)','brand',f.brand||'','text','maxlength="100"')}${this.field('Código de barras (opcional)','barcode',f.barcode||'','text','maxlength="40"')}${this.select('Unidad','unit',unit,[['g','Gramos (g)'],['ml','Mililitros (ml)']])}${this.field('Cantidad de referencia de la etiqueta','baseQuantity',100,'number','required min="0.1" max="10000" step="0.1"')}${this.field('Categoría','category',f.category||'Mis productos','text','required maxlength="80"')}${[['Calorías en esa cantidad','kcal'],['Proteína (g)','protein'],['Carbohidratos (g)','carbs'],['Grasa (g)','fat'],['Costo de esa cantidad (opcional)','cost']].map(([l,k])=>this.field(l,k,f[k]??(k==='cost'?'':0),'number',`${k==='cost'?'':'required'} min="0" max="10000" step="0.01"`)).join('')}</div>${this.actions('Guardar producto')}</form>`);}
    portionForm(){this.calculationId=null;this.modal('Calculadora de porciones',`<form id="portions-form"><p>Elige dos alimentos y una meta. Al calcular se guardarán las porciones en tu diario. Vuelve a calcular para corregir el mismo registro.</p><div class="form-grid">${this.field('Fecha','date',this.date,'date',`required max="${this.day()}"`)}${this.select('Momento','mealType','Almuerzo',this.mealOptions())}${this.picker('Alimento 1','first',this.state.foods[0]?.id)}${this.picker('Alimento 2','second',this.state.foods.find(f=>f.name==='Pechuga de pollo cocida')?.id||this.state.foods[1]?.id)}${this.field('Meta de calorías','kcal',500,'number','required min="1" max="10000"')}${this.field('Meta de proteína (g)','protein',30,'number','required min="0" max="400"')}</div>${this.actions('Calcular y guardar en el diario')}<div id="portion-result" role="status"></div></form>`);}
    mealOptions(){return ['Desayuno','Almuerzo','Cena','Merienda','Otro'].map(v=>[v,v]);}
    logForm(foodId,entryId){const entry=this.state.meals.find(m=>m.id===entryId);this.draft={id:entry?.id||this.id(),name:entry?.name||'',date:entry?.date||this.date,mealType:entry?.mealType||'Almuerzo',items:entry?.items?.map(i=>({foodId:i.foodId,grams:i.grams,snapshot:structuredClone(i)}))||[{foodId:foodId||this.state.foods[0]?.id||'',grams:100}],editing:!!entry};this.drawLog();}
    drawLog(){const d=this.draft;this.modal(d.editing?'Editar registro':'Registrar comida',`<form id="nutrition-log-form"><div class="form-grid">${this.field('Fecha','date',d.date,'date',`required max="${this.day()}"`)}${this.select('Momento','mealType',d.mealType,this.mealOptions())}${this.field('Nombre de la comida (opcional)','name',d.name,'text','maxlength="120"')}</div>${d.editing?'<p class="source-note">Los alimentos conservan los valores y la unidad del registro original. Al cambiar la cantidad se ajustan en la misma proporción.</p>':''}${this.ingredientRows(d.items)}${this.b('Agregar otro alimento','nutrition-add-row')}${this.actions(d.editing?'Guardar cambios':'Calcular y guardar comida')}</form>`);}
    ingredientRows(items){return items.map((i,index)=>`<div class="ingredient-row"><div class="form-grid">${this.picker('Alimento '+(index+1),'item_'+index,i.foodId,i.snapshot?.unit,i.snapshot)}${this.field(`Cantidad (${i.snapshot?.unit||this.state.foods.find(f=>f.id===i.foodId)?.unit||'g'})`,'qty_'+index,i.grams,'number','required min="0.1" max="10000" step="0.1"')}</div>${items.length>1?this.b('Quitar ingrediente','nutrition-remove-row',`data-index="${index}"`):''}</div>`).join('');}
    rememberDraft(){const form=document.querySelector('#nutrition-log-form');if(!form)return;const data=Object.fromEntries(new FormData(form));Object.assign(this.draft,{name:data.name,date:data.date,mealType:data.mealType,items:this.readItems(data,this.draft.items.length,this.draft.items)});}
    readItems(data,count,originals=[]){return Array.from({length:count},(_,i)=>({foodId:data['item_'+i],grams:Number(data['qty_'+i]),...(originals[i]?.snapshot?.foodId===data['item_'+i]?{snapshot:originals[i].snapshot}:{})}));}
    recipeForm(rid){const r=this.state.recipes.find(r=>r.id===rid);this.recipeDraft={id:r?.id||this.id(),name:r?.name||'',instructions:r?.instructions||'',items:r?.items?.map(i=>({...i}))||[{foodId:this.state.foods[0]?.id||'',grams:100}]};this.drawRecipe();}
    drawRecipe(){const r=this.recipeDraft;this.modal('Tu receta',`<form id="recipe-form">${this.field('Nombre','name',r.name,'text','required maxlength="100"')}${this.ingredientRows(r.items).replaceAll('nutrition-remove-row','nutrition-recipe-remove')}${this.b('Agregar ingrediente','nutrition-recipe-add')}<label>Preparación<textarea name="instructions" maxlength="3000">${this.esc(r.instructions)}</textarea></label>${this.actions('Guardar receta')}</form>`);}
    rememberRecipe(){const f=document.querySelector('#recipe-form');if(!f)return;const data=Object.fromEntries(new FormData(f));Object.assign(this.recipeDraft,{name:data.name,instructions:data.instructions,items:this.readItems(data,this.recipeDraft.items.length,this.recipeDraft.items)});}
    record(entry){const previous=this.state.meals.find(m=>m.id===entry.id);if(previous&&previous.date!==entry.date)FitnessNutrition.captureDay(this.state,previous.date,this.day()).complete=false;const record=FitnessNutrition.captureDay(this.state,entry.date,this.day());record.complete=false;this.state.meals=FitnessNutrition.upsert(this.state.meals||[],entry);this.save();this.date=entry.date;}
    handlesAction(name){return name.startsWith('nutrition-')||['food-edit','recipe','portions','meal','meal-remove'].includes(name);}
    action(name,b){const id=b.dataset.id;
      if(name==='nutrition-water-add'){this.state.waterLogs||=[];this.state.waterLogs.push({id:this.id(),date:this.date,ml:Number(this.state.config.waterGlassMl)||250});this.save();return this.renderApp();}
      if(name==='nutrition-water-remove'){const last=this.state.waterLogs.filter(w=>w.date===this.date).at(-1);if(last){this.state.waterLogs=this.state.waterLogs.filter(w=>w.id!==last.id);this.save();}return this.renderApp();}
      if(name==='nutrition-delete-food'||name==='nutrition-delete-recipe')return this.modal('Eliminar de tu catálogo',`<p>Se eliminará este elemento del catálogo. Las comidas ya registradas conservarán sus cantidades y macros.</p>${this.b('Confirmar eliminación',name+'-confirm',`data-id="${id}"`,'danger')}`);
      if(name==='nutrition-delete-food-confirm'){FitnessNutrition.preserveFoodReferences(this.state,id);this.state.foods=this.state.foods.filter(f=>f.id!==id);this.state.config.deletedFoodIds=[...new Set([...(this.state.config.deletedFoodIds||[]),id])];this.save();this.close();return this.renderApp();}
      if(name==='nutrition-delete-recipe-confirm'){this.state.recipes=this.state.recipes.filter(r=>r.id!==id);this.save();this.close();return this.renderApp();}
      if(name==='nutrition-restaurant')return this.restaurantForm(b.dataset.restaurant,id);
      if(name==='nutrition-drink-zero'||name==='nutrition-drink-water'){this.rememberRestaurant();const index=Number(b.dataset.index);this.restaurantDraft.components[index]={...this.restaurantDraft.components[index],...structuredClone(FitnessRestaurants.drinkAlternatives[name.endsWith('zero')?0:1]),included:true};return this.drawRestaurant();}

      if(name==='nutrition-export')return FitnessIO.download(FitnessIO.csvDatasets(this.state)['comidas.csv'],'impulso-diario-calorico-'+this.day()+'.csv','text/csv;charset=utf-8');
      if(name==='food-edit')return this.foodForm(id);if(name==='recipe')return this.recipeForm(id);if(name==='portions')return this.portionForm();
      if(name==='nutrition-view-diary'){this.close();return this.renderApp();}
      if(name==='nutrition-log')return this.logForm(id);if(name==='nutrition-edit'){const entry=this.state.meals.find(m=>m.id===id);return entry?.source==='restaurant'?this.restaurantForm(null,null,entry):this.logForm(null,id);}
      if(name==='nutrition-add-row'){this.rememberDraft();this.draft.items.push({foodId:this.state.foods[0]?.id||'',grams:100});return this.drawLog();}
      if(name==='nutrition-remove-row'){this.rememberDraft();this.draft.items.splice(Number(b.dataset.index),1);return this.drawLog();}
      if(name==='nutrition-recipe-add'){this.rememberRecipe();this.recipeDraft.items.push({foodId:this.state.foods[0]?.id||'',grams:100});return this.drawRecipe();}
      if(name==='nutrition-recipe-remove'){this.rememberRecipe();this.recipeDraft.items.splice(Number(b.dataset.index),1);return this.drawRecipe();}
      if(name==='nutrition-more'){this.limit+=12;document.querySelector('#food-results').innerHTML=this.catalogRows();return;}
      if(name==='nutrition-date'||name==='nutrition-today'){this.date=b.dataset.date||this.day();return this.renderApp();}
      if(name==='nutrition-complete'){const d=FitnessNutrition.captureDay(this.state,this.date,this.day());d.complete=!d.complete;this.save();return this.renderApp();}
      if(name==='meal-remove'){const old=this.state.meals.find(m=>m.id===id);if(!old)return;FitnessNutrition.captureDay(this.state,old.date,this.day()).complete=false;this.state.meals=this.state.meals.filter(m=>m.id!==id);this.save();return this.renderApp();}
      if(name==='meal'){const r=this.state.recipes.find(r=>r.id===id);return this.modal('Registrar receta',`<form id="meal-form" data-id="${r.id}"><h3>${this.esc(r.name)}</h3><div class="form-grid">${this.field('Fecha','date',this.date,'date',`required max="${this.day()}"`)}${this.select('Momento','mealType','Almuerzo',this.mealOptions())}${this.field('Número de preparaciones (0,5 = media)','factor',1,'number','required min="0.05" max="20" step="0.05"')}</div>${this.actions('Registrar comida')}</form>`);}
    }
    handlesForm(kind){return ['restaurant-form','nutrition-log-form','food-form','recipe-form','portions-form','meal-form'].includes(kind);}
    submit(form){const v=Object.fromEntries(new FormData(form)),kind=form.id,{state}=this;
      if(v.date&&(!FitnessNutrition.validDate(v.date)||v.date>this.day()))throw Error('Registra una fecha de hoy o anterior.');
      if(kind==='restaurant-form'){this.rememberRestaurant();const d=this.restaurantDraft,items=FitnessNutrition.restaurantSnapshot(d.components,'restaurant-'+d.id);if(!items.length)throw Error('Incluye al menos un componente.');this.record({id:d.id,date:d.date,name:d.name,mealType:d.mealType,items,...FitnessNutrition.totals(items),source:'restaurant',restaurantKey:d.key,estimated:items.some(i=>i.estimated)});if(d.key){this.state.config.restaurantTemplates||={};this.state.config.restaurantTemplates[d.key]=structuredClone(d.components);this.save();}}
      if(kind==='food-form'){const base=Number(v.baseQuantity);if(!(base>0))throw Error('Revisa la cantidad de referencia.');const item={id:form.dataset.id||this.id(),name:v.name,brand:v.brand,barcode:v.barcode,category:v.category,unit:v.unit,source:'Etiqueta o valores editados por ti',priceConfigured:v.cost!==''};for(const k of ['kcal','protein','carbs','fat','cost'])item[k]=Number(v[k]||0)*100/base;if(item.unit==='g'&&item.protein+item.carbs+item.fat>110)throw Error('Revisa los gramos de macros y la cantidad de referencia.');const old=state.foods.findIndex(f=>f.id===item.id);if(old>=0)state.foods[old]=item;else state.foods.push(item);this.save();}
      if(kind==='recipe-form'){this.rememberRecipe();FitnessNutrition.snapshot(state.foods,this.recipeDraft.items);state.recipes=[...state.recipes.filter(r=>r.id!==this.recipeDraft.id),structuredClone(this.recipeDraft)];this.save();}
      if(kind==='nutrition-log-form'){this.rememberDraft();const items=FitnessNutrition.snapshot(state.foods,this.draft.items),entry={id:this.draft.id,date:v.date,mealType:v.mealType,name:v.name||items.map(i=>i.name).join(' + '),items,...FitnessNutrition.totals(items),source:'manual'};this.record(entry);}
      if(kind==='meal-form'){const r=state.recipes.find(r=>r.id===form.dataset.id),items=FitnessNutrition.snapshot(state.foods,r.items.map(i=>({...i,grams:i.grams*Number(v.factor)})));this.record({id:this.id(),date:v.date,mealType:v.mealType,name:r.name,items,...FitnessNutrition.totals(items),source:'recipe'});}
      if(kind==='portions-form'){const a=state.foods.find(f=>f.id===v.first),b=state.foods.find(f=>f.id===v.second),portions=FitnessNutrition.solve(a,b,Number(v.kcal),Number(v.protein)),items=FitnessNutrition.snapshot(state.foods,portions);this.calculationId||=this.id();const entry={id:this.calculationId,date:v.date,mealType:v.mealType,name:items.map(i=>i.name).join(' + '),items,...FitnessNutrition.totals(items),source:'portion-calculator'};this.record(entry);document.querySelector('#portion-result').innerHTML=`<section class="card mint"><h3>Guardado en tu diario</h3>${items.map(i=>`<p>${this.fmt(i.grams,1)} ${this.esc(i.unit)} de ${this.esc(i.name)}</p>`).join('')}<p>${this.fmt(entry.kcal)} kcal · ${this.fmt(entry.protein,1)} g proteína</p><p>${this.dateText(entry.date)} · ${this.esc(entry.mealType)}</p><p class="source-note">Recalcular aquí actualiza este registro, sin duplicarlo.</p>${this.b('Ver mi diario','nutrition-view-diary')}</section>`;return;}
      this.close();this.renderApp();this.notice(kind==='food-form'?'Producto guardado. Tus comidas anteriores conservan sus valores.':kind==='recipe-form'?'Receta guardada.':'Comida guardada en tu diario.');
    }
    input(el){if(el.closest('#restaurant-form'))this.restaurantPreview();if(el.id==='food-query'){this.query=el.value;this.limit=12;document.querySelector('#food-results').innerHTML=this.catalogRows();}if(el.dataset.foodFilter){const select=el.closest('.food-picker').querySelector('select'),value=select.value,selectedText=select.selectedOptions[0]?.textContent,list=this.foods(el.value);if(!list.some(f=>f.id===value)){const current=this.state.foods.find(f=>f.id===value);if(current)list.unshift(current);}if(value&&!list.some(f=>f.id===value))list.unshift({id:value,name:selectedText||'Registro conservado',unit:'g'});select.innerHTML=list.map(f=>`<option value="${f.id}" ${f.id===value?'selected':''}>${this.esc(f.name)} · 100 ${this.esc(f.unit||'g')}</option>`).join('');}}
    change(el){if(el.id==='water-glass-ml'){this.state.config.waterGlassMl=Number(el.value);this.save();return this.renderApp();}if(el.closest('#restaurant-form'))this.restaurantPreview();if(el.id==='diary-date'){if(!FitnessNutrition.validDate(el.value)||el.value>this.day()){this.notice('Selecciona una fecha válida de hoy o anterior.');el.value=this.date;return;}this.date=el.value;this.renderApp();}if(el.id==='food-category'){this.category=el.value;this.limit=12;document.querySelector('#food-results').innerHTML=this.catalogRows();}if(el.name?.startsWith('item_')){const index=el.name.slice(5),unit=(el.closest('#nutrition-log-form')&&this.draft?.items[Number(index)]?.snapshot?.foodId===el.value?this.draft.items[Number(index)].snapshot.unit:null)||this.state.foods.find(f=>f.id===el.value)?.unit||'g',label=el.closest('form').querySelector(`[name="qty_${index}"]`).parentElement;label.firstChild.textContent=`Cantidad (${unit})`;}}
  };
})(globalThis);
