/* Local menu names verified September 2026. Portion weights and nutrition are estimates, never official Panama nutrition. */
(function(root,factory){const api=factory(typeof module==='object'?require('./food-catalog.js'):root.FitnessFoodCatalog);if(typeof module==='object'&&module.exports)module.exports=api;else root.FitnessRestaurants=api;})(globalThis,(catalog)=>{
  const component=(name,parts,kind='main')=>{const out={name,kind,quantityLabel:parts.map(([id,g])=>g+' g de '+catalog.foods.find(f=>f.id==='usda-'+id).name).join(' + '),quantity:1,estimated:true,kcal:0,protein:0,carbs:0,fat:0,cost:0};for(const [id,g] of parts){const f=catalog.foods.find(f=>f.id==='usda-'+id);for(const key of ['kcal','protein','carbs','fat'])out[key]+=f[key]*g/100;}return out;};
  const soda=()=>component('Soda regular · referencia 350 g de bebida',[[174852,350]],'drink');
  const fries=()=>component('Papas fritas · porción estimada 100 g',[[170721,100]],'side');
  const chicken=()=>component('Pollo apanado · porción estimada 150 g',[[173321,150]]);
  const chicha=()=>component('Chicha de nance · receta estimada, no oficial',[[167789,70],[169655,30]],'drink');
  const item=(id,name,components,notes='')=>({id,name,components,estimated:true,notes});
  const vegetables=()=>component('Vegetales y guacamole · aproximación',[[171705,40],[170457,30],[170000,10],[169247,20]],'side');
  const cream=()=>component('Crema agria y queso · aproximación',[[173443,25],[170845,25]],'side');
  const rice=()=>component('Arroz cocido · 150 g estimados',[[168878,150]],'side');
  const meat=()=>component('Pollo · 100 g estimados',[[171477,100]]);
  const restaurants=[
    {id:'mcd',name:"McDonald's Panamá",sourceUrl:'https://www.mcdonalds.com.pa/menu/hamburguesas',notes:'Nombres de menú local. Nutrición calculada con referencias USDA de EE. UU. de 2018 y porciones supuestas; no equivale a la ficha panameña actual.',items:[item('bigmac','Combo Big Mac',[component('Big Mac · referencia estimada 215 g',[[170720,215]]),fries(),soda()]),item('gourmet','Combo McDoble Gourmet',[component('McDoble Gourmet · equivalente estimado, 200 g',[[170374,200]]),fries(),soda()],'El equivalente USDA no reproduce queso suizo, cebolla caramelizada y salsa de la receta local; edita con información del restaurante.'),item('cuarto','Combo Cuarto de Libra con queso',[component('Cuarto de Libra con queso · 200 g estimados',[[170719,200]]),fries(),soda()])]},
    {id:'pio',name:'Pío Pío',sourceUrl:'https://piopiolomio.com/products/combo-5-pechuguitas-apanadas',notes:'Combo #5 verificado: pechuguitas, papas o arroz con vegetales y soda mediana. Gramajes y nutrición estimados, no publicados por la marca.',items:[item('combo5','Combo #5 · Pechuguitas apanadas',[chicken(),fries(),soda(),component('Salsa · equivalente de mayonesa 20 g',[[171009,20]],'side')],'Puedes quitar las papas y añadir arroz, o editar la salsa según lo que consumiste.'),item('combo5arroz','Combo #5 · con arroz',[chicken(),rice(),soda()],'Arroz simple como aproximación; aceite y vegetales de la preparación real pueden variar.'),item('nance','Chicha de nance',[chicha()],'Pío Pío publica chichas de fruta; disponibilidad de nance y receta exacta no verificadas. Referencia casera de 70 g de pulpa + 30 g de azúcar diluidos en agua, no valor oficial.') ]},
    {id:'bk',name:'Burger King (BGK)',sourceUrl:'https://www.burgerkinglatino.com/es/menu-item/whopper',notes:'Se interpreta BGK como Burger King. Referencia regional: disponibilidad y tamaño dependen del local. Datos USDA EE. UU. 2018, no nutrición oficial de Panamá.',items:[item('whopper','Combo Whopper',[component('Whopper sin queso · 290 g estimados',[[170727,290]]),component('Papas BK · 100 g estimados',[[170327,100]],'side'),soda()]),item('whopperqueso','Combo Whopper con queso',[component('Whopper con queso · 300 g estimados',[[170728,300]]),fries(),soda()])]},
    {id:'cuates',name:'Trescuates Panamá',sourceUrl:'https://www.degustapanama.com/panama/restaurante/trescuates_108530/menu',notes:'Composición consultada en el menú publicado en Degusta; fuente secundaria, no ficha nutricional oficial. Las cantidades son supuestos editables.',items:[item('burrito','Burrito de pollo',[component('Tortilla de harina · 70 g estimados',[[173242,70]]),rice(),meat(),vegetables(),cream()]),item('bowl','Bowl de pollo',[rice(),component('Frijoles · 80 g estimados',[[173735,80]]),meat(),vegetables(),cream()]),item('tacos','Tres tacos de pollo',[component('3 tortillas · 75 g estimados',[[173241,75]]),meat(),vegetables(),cream()]),item('quesadilla','Quesadilla de pollo',[component('Tortilla de harina · 70 g estimados',[[173242,70]]),meat(),cream()])]},
    {id:'local',name:'Comida local · recetas aproximadas',sourceUrl:'https://fdc.nal.usda.gov/download-datasets/',notes:'Preparaciones genéricas para editar según la porción y los ingredientes que comiste. No representan una receta comercial específica.',items:[item('salchipapas','Salchipapas',[component('Papas fritas · 200 g estimados',[[170721,200]],'side'),component('Salchicha · 100 g estimados',[[171633,100]]),component('Kétchup · 25 g',[[168556,25]],'side'),component('Mayonesa · 20 g',[[171009,20]],'side')]) ]}
  ];
  return {restaurants,drinkAlternatives:[{name:'Soda zero (consulta etiqueta)',quantity:1,kcal:0,protein:0,carbs:0,fat:0,kind:'drink',estimated:true},{name:'Agua',quantity:1,kcal:0,protein:0,carbs:0,fat:0,kind:'drink',estimated:false}]};
});
