const {chromium}=require('C:/Users/barri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'America/Panama',acceptDownloads:true});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const btn=n=>page.getByRole('button',{name:n,exact:true});const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('impulsoTransformacion:v1:local')));const fill=async(values)=>{for(const [name,value]of Object.entries(values))await page.locator('[name="'+name+'"]').fill(String(value));};
try{
await page.goto('http://127.0.0.1:8089/transformacion/#perfil');await page.waitForSelector('#profile-form');assert.equal(await page.locator('.brand-logo').evaluate(e=>e.naturalWidth>0),true);assert.equal(await page.locator('[name=activityFactor]').count(),0);
await fill({name:'Prueba TNC',age:30,heightCm:180,initialWeightKg:80});await page.locator('[name=activityLevel]').selectOption('moderate');await page.locator('[name=profilePhoto]').setInputFiles('transformacion/tnc-logo.png');await btn('Guardar perfil').click();await page.waitForSelector('.profile-photo');assert.ok((await saved()).profile.photoMediaId);await page.reload();await page.waitForSelector('.profile-photo');assert.ok(await page.locator('.profile-photo').evaluate(e=>e.naturalWidth>0));
await btn('Recalcular TDEE').click();await btn('Aplicar este objetivo').click();const initial=(await saved()).targets;assert.equal(initial.tdee,2759);
await btn('Ajustar calorías').click();await btn('−50 kcal').click();await btn('Guardar nuevo objetivo').click();assert.equal((await saved()).targets.calories,initial.calories);await page.locator('[name=acknowledge]').check();await btn('Guardar nuevo objetivo').click();assert.equal((await saved()).targets.calories,initial.calories-50);assert.notEqual((await saved()).targets.carbs,initial.carbs);
await page.locator('[data-weight-unit]').selectOption('lb');await btn('Guardar perfil').click();assert.equal((await saved()).profile.initialWeightKg,80);await btn('Progreso').click();assert.ok(await page.locator('svg[aria-label="Peso inicial y evolución en lb"]').count());await btn('Registrar peso').click();await fill({weightKg:176});await btn('Guardar peso').click();assert.ok(Math.abs((await saved()).weights[0].weightKg-79.83225712)<.00001);await page.screenshot({path:'transformacion/qa-tnc-progress.png',fullPage:true});
await btn('Entrenar').click();await btn('Crear rutina').click();await fill({name:'Rutina TNC comprobada'});await btn('Agregar ejercicio propio').click();await fill({name:'Remo TNC',muscles:'Espalda',sets:1,plannedWeightKg:100,restSeconds:1});await btn('Agregar a la rutina').click();await btn('Guardar rutina').click();await page.locator('article').filter({has:page.getByRole('heading',{name:'Rutina TNC comprobada',exact:true})}).getByRole('button',{name:'Empezar',exact:true}).click();assert.equal(await page.locator('[data-set=weightKg]').inputValue(),'100');await page.locator('[data-set=reps]').fill('10');await page.getByRole('button',{name:'Completar Remo TNC serie 1',exact:true}).click();await page.waitForSelector('#rest-bar.rest-complete');assert.match(await page.locator('#rest-bar').innerText(),/Descanso terminado/);assert.equal(await page.locator('.set-row.done button').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(120, 231, 173)');await page.reload();await page.waitForSelector('#rest-bar.rest-complete');assert.ok(Math.abs((await saved()).activeSession.exercises[0].sets[0].weightKg-45.359237)<1e-8);
await btn('Terminar y guardar').click();const downloadEvent=page.waitForEvent('download');await btn('Descargar imagen').click();const download=await downloadEvent;await download.saveAs('transformacion/qa-tnc-session.png');assert.equal(await download.failure(),null);await btn('Cerrar').click();
await btn('Comida').click();await page.getByRole('button',{name:'Tomé un vaso · 250 ml',exact:true}).click();await page.getByRole('button',{name:'Tomé un vaso · 250 ml',exact:true}).click();assert.equal((await saved()).waterLogs.length,2);await page.reload();assert.match(await page.locator('.water-card').innerText(),/0[.,]5 L/);await btn('Quitar último vaso').click();assert.equal((await saved()).waterLogs.length,1);
await btn('Combo #5 · Pechuguitas apanadas').click();const before=await page.locator('#restaurant-total').innerText();await page.locator('[name=include_1]').uncheck();await btn('Cambiar a soda zero').click();const after=await page.locator('#restaurant-total').innerText();assert.notEqual(before,after);await btn('Guardar comida en el diario').click();const meal=(await saved()).meals.at(-1);assert.equal(meal.source,'restaurant');assert.equal(meal.items.some(i=>i.name.startsWith('Papas')),false);const original=meal.kcal;await btn('Editar registro').click();await page.locator('[name=quantity_0]').fill('2');await btn('Guardar comida en el diario').click();assert.ok((await saved()).meals[0].kcal>original);assert.equal((await saved()).meals.length,1);
await btn('Nueva receta').click();await page.locator('#recipe-form [name=name]').fill('Receta protegida');await btn('Guardar receta').click();const firstId=(await saved()).recipes[0].items[0].foodId;await page.locator('#food-results [data-action=nutrition-delete-food]').first().click();await btn('Confirmar eliminación').click();assert.equal((await saved()).foods.some(f=>f.id===firstId),false);await page.reload();assert.equal((await saved()).foods.some(f=>f.id===firstId),false);await btn('Agregar al día').click();await btn('Registrar comida').click();await page.getByRole('button',{name:'Editar registro',exact:true}).last().click();assert.ok(await page.locator('[name=item_0]').inputValue());await btn('Guardar cambios').click();await btn('Eliminar receta').click();await btn('Confirmar eliminación').click();assert.equal((await saved()).recipes.length,0);
await page.screenshot({path:'transformacion/qa-tnc-food.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'transformacion/qa-tnc-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS TNC: logo, profile photo, automatic activity, calorie warning, kg/lb, graph, rest, green sets, PNG, water, restaurant editing, deletion and preservation.');
}catch(e){await page.screenshot({path:'transformacion/qa-tnc-failure.png',fullPage:true});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
