const {chromium}=require('C:/Users/barri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});
try{await page.goto('http://127.0.0.1:8089/transformacion/');
const bytes=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=160;c.height=90;document.body.appendChild(c);const ctx=c.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,160,90);const stream=c.captureStream(0),rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),chunks=[];rec.ondataavailable=e=>chunks.push(e.data);const done=new Promise(r=>rec.onstop=r);rec.start();let frame=0;const t=setInterval(()=>{ctx.fillStyle=frame++%2?'#cfbaff':'#141414';ctx.fillRect(0,0,160,90);stream.getVideoTracks()[0].requestFrame();},80);await new Promise(r=>setTimeout(r,1800));rec.stop();await done;clearInterval(t);stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())];});
console.log('Fixture de video:',bytes.length,'bytes');await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.getByRole('button',{name:'Editar rutina',exact:true}).first().click();await page.locator('#routine-form [data-action=exercise-edit][data-index="0"]').click();await page.locator('#exercise-form [name=media]').setInputFiles({name:'tecnica.webm',mimeType:'video/webm',buffer:Buffer.from(bytes)});await page.getByRole('button',{name:'Agregar a la rutina',exact:true}).click();await page.getByRole('button',{name:'Guardar rutina',exact:true}).click();
await page.getByRole('button',{name:'Empezar',exact:true}).last().click();await page.getByRole('button',{name:'Técnica / multimedia',exact:true}).first().click();await page.waitForFunction(()=>document.querySelector('#modal video')?.readyState>=1);assert.ok(await page.locator('video').evaluate(v=>v.videoWidth>0));await page.locator('video').evaluate(v=>v.play());await page.waitForTimeout(200);assert.ok(await page.locator('video').evaluate(v=>v.currentTime>0));await page.screenshot({path:'transformacion/qa-video-mobile.png'});await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Técnica / multimedia',exact:true}).first().click();await page.waitForFunction(()=>document.querySelector('#modal video')?.readyState>=1);await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'transformacion/qa-session-viewport.png'});console.log('PASS: video local se reproduce y permanece disponible después de recargar.');}catch(error){console.log((await page.locator("body").innerText()).slice(-4000));console.log(await page.locator("#modal-body").innerHTML());console.log(await page.locator("video").evaluate(v=>({error:v.error?.message,code:v.error?.code,ready:v.readyState,network:v.networkState})));await page.screenshot({path:"transformacion/qa-video-failure.png"});throw error;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});



